name: fdl_server
description: A simple command-line application.
version: 1.0.0

environment:
    sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
    pedantic: ^1.10.0
dependencies: 
    shelf: ^1.2.0
    shelf_router: ^1.1.1
