name: fdl_server
description: The REST and WS api for FreedomLand ecosystem.
version: 1.0.0

environment:
    sdk: '>=2.13.0 <3.0.0'

dev_dependencies:
    lints: ^1.0.1
dependencies:
    dart_minecraft: ^0.4.0
    shelf: ^1.2.0
    shelf_router: ^1.1.1
    firebase_admin: ^0.2.0-dev.1
    mongo_dart: ^0.7.1
