name: fdl_server
description: A simple command-line application.
version: 1.0.0

environment:
    sdk: '>=2.13.0 <3.0.0'

dev_dependencies:
    pedantic: ^1.10.0
dependencies:
    dart_minecraft: ^0.4.0
    shelf: ^1.2.0
    shelf_router: ^1.1.1
    firebase_admin: ^0.2.0-dev.1
    mongo_dart: ^0.7.1
